enableScripts: true

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthIdent: '${NEXUS_CREDENTIALS:-}'

npmAuthToken: '${PLACEHOLDER:-}'

npmRegistryServer: 'https://nexus-dev.pcbltools.ru/repository/npm-group/'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-ldap-auth.cjs
    spec: node_modules/@ecp/yarn-ecp-ldap-auth-plugin/index.js

yarnPath: .yarn/releases/yarn-3.2.0.cjs
