export const iconsStore = {
  artificial: './icons/artificial.tsx',
  communication: './icons/communication.tsx',
  creative: './icons/creative.tsx',
  critical: './icons/critical.tsx',
  cyber: './icons/cyber.tsx',
  data: './icons/data.tsx',
  decision: './icons/decision.tsx',
  development: './icons/development.tsx',
  digital: './icons/digital.tsx',
  'digital-skills': './icons/digital-skills.tsx',
  emotional: './icons/emotional.tsx',
  'digital-communication': './icons/digital-communication.tsx',
  information: './icons/information.tsx',
  literacy: './icons/literacy.tsx',
  logic: './icons/logic.tsx',
  management: './icons/management.tsx',
  mind: './icons/mind.tsx',
  programming: './icons/programming.tsx',
  right: './icons/right.tsx',
  teamwork: './icons/teamwork.tsx',
  time: './icons/time.tsx',
  thinking: './icons/thinking.tsx',
  'soft-skills': './icons/soft-skills.tsx',
};
