const caretIconStore = {
  'caret-circle-double-right-solid': './caret/circleDoubleRightSolid.tsx',
  'caret-double-right-solid': './caret/doubleRightSolid.tsx',
  'caret-circle-double-left-solid': './caret/circleDoubleLeftSolid.tsx',
  'caret-double-left-solid': './caret/doubleLeftSolid.tsx',
  'caret-circle-double-down-solid': './caret/circleDoubleDownSolid.tsx',
  'caret-double-down-solid': './caret/doubleDownSolid.tsx',
  'caret-circle-double-up-solid': './caret/circleDoubleUpSolid.tsx',
  'caret-double-up-solid': './caret/doubleUpSolid.tsx',
  'caret-circle-right-solid': './caret/circleRightSolid.tsx',
  'caret-right-solid': './caret/rightSolid.tsx',
  'caret-circle-left-solid': './caret/circleLeftSolid.tsx',
  'caret-left-solid': './caret/leftSolid.tsx',
  'caret-circle-down-solid': './caret/circleDownSolid.tsx',
  'caret-down-solid': './caret/downSolid.tsx',
  'caret-circle-up-solid': './caret/circleUpSolid.tsx',
  'caret-up-solid': './caret/upSolid.tsx',
  'caret-circle-double-right': './caret/circleDoubleRight.tsx',
  'caret-double-right': './caret/doubleRight.tsx',
  'caret-circle-double-left': './caret/circleDoubleLeft.tsx',
  'caret-double-left': './caret/doubleLeft.tsx',
  'caret-circle-double-down': './caret/circleDoubleDown.tsx',
  'caret-double-down': './caret/doubleDown.tsx',
  'caret-circle-double-up': './caret/circleDoubleUp.tsx',
  'caret-double-up': './caret/doubleUp.tsx',
  'caret-circle-right': './caret/circleRight.tsx',
  'caret-right': './caret/right.tsx',
  'caret-circle-left': './caret/circleLeft.tsx',
  'caret-left': './caret/left.tsx',
  'caret-circle-down': './caret/circleDown.tsx',
  'caret-down': './caret/down.tsx',
  'caret-circle-up': './caret/circleUp.tsx',
  'caret-up': './caret/up.tsx',
};

export default caretIconStore;
