const developmentIconStore = {
  'development-database-solid': './development/databaseSolid.tsx',
  'development-magnet-straight-solid': './development/magnetStraightSolid.tsx',
  'development-cpu-solid': './development/cpuSolid.tsx',
  'development-magnet-solid': './development/magnetSolid.tsx',
  'development-git-pull-request-solid': './development/gitPullRequestSolid.tsx',
  'development-terminal-solid': './development/terminalSolid.tsx',
  'development-code-simple-solid': './development/codeSimpleSolid.tsx',
  'development-git-merge-solid': './development/gitMergeSolid.tsx',
  'development-code-solid': './development/codeSolid.tsx',
  'development-git-fork-solid': './development/gitForkSolid.tsx',
  'development-bug-droid-solid': './development/bugDroidSolid.tsx',
  'development-git-diff-solid': './development/gitDiffSolid.tsx',
  'development-bug-beetle-solid': './development/bugBeetleSolid.tsx',
  'development-git-commit-solid': './development/gitCommitSolid.tsx',
  'development-bug-solid': './development/bugSolid.tsx',
  'development-git-branch-solid': './development/gitBranchSolid.tsx',
  'development-tree-structure-solid': './development/treeStructureSolid.tsx',
  'development-database': './development/database.tsx',
  'development-magnet-straight': './development/magnetStraight.tsx',
  'development-cpu': './development/cpu.tsx',
  'development-magnet': './development/magnet.tsx',
  'development-git-pull-request': './development/gitPullRequest.tsx',
  'development-terminal': './development/terminal.tsx',
  'development-code-simple': './development/codeSimple.tsx',
  'development-git-merge': './development/gitMerge.tsx',
  'development-code': './development/code.tsx',
  'development-git-fork': './development/gitFork.tsx',
  'development-bug-droid': './development/bugDroid.tsx',
  'development-git-diff': './development/gitDiff.tsx',
  'development-bug-beetle': './development/bugBeetle.tsx',
  'development-git-commit': './development/gitCommit.tsx',
  'development-bug': './development/bug.tsx',
  'development-git-branch': './development/gitBranch.tsx',
  'development-tree-structure': './development/treeStructure.tsx',
};

export default developmentIconStore;
