const timeIconStore = {
  'time-hourglass-simple-low-solid': './time/hourglassSimpleLowSolid.tsx',
  'time-timer-solid': './time/timerSolid.tsx',
  'time-hourglass-simple-medium-solid': './time/hourglassSimpleMediumSolid.tsx',
  'time-alarm-solid': './time/alarmSolid.tsx',
  'time-hourglass-simple-high-solid': './time/hourglassSimpleHighSolid.tsx',
  'time-watch-solid': './time/watchSolid.tsx',
  'time-clock-afternoon-solid': './time/clockAfternoonSolid.tsx',
  'time-hourglass-simple-solid': './time/hourglassSimpleSolid.tsx',
  'time-clock-solid': './time/clockSolid.tsx',
  'time-hourglass-low-solid': './time/hourglassLowSolid.tsx',
  'time-calendar-x-solid': './time/calendarXSolid.tsx',
  'time-hourglass-medium-solid': './time/hourglassMediumSolid.tsx',
  'time-calendar-blank-solid': './time/calendarBlankSolid.tsx',
  'time-clock-counter-clockwise-solid': './time/clockCounterClockwiseSolid.tsx',
  'time-hourglass-high-solid': './time/hourglassHighSolid.tsx',
  'time-calendar-solid': './time/calendarSolid.tsx',
  'time-clock-clockwise-solid': './time/clockClockwiseSolid.tsx',
  'time-hourglass-solid': './time/hourglassSolid.tsx',
  'time-hourglass-simple-low': './time/hourglassSimpleLow.tsx',
  'time-timer': './time/timer.tsx',
  'time-hourglass-simple-medium': './time/hourglassSimpleMedium.tsx',
  'time-alarm': './time/alarm.tsx',
  'time-hourglass-simple-high': './time/hourglassSimpleHigh.tsx',
  'time-watch': './time/watch.tsx',
  'time-clock-afternoon': './time/clockAfternoon.tsx',
  'time-hourglass-simple': './time/hourglassSimple.tsx',
  'time-clock': './time/clock.tsx',
  'time-hourglass-low': './time/hourglassLow.tsx',
  'time-calendar-x': './time/calendarX.tsx',
  'time-hourglass-medium': './time/hourglassMedium.tsx',
  'time-calendar-blank': './time/calendarBlank.tsx',
  'time-clock-counter-clockwise': './time/clockCounterClockwise.tsx',
  'time-hourglass-high': './time/hourglassHigh.tsx',
  'time-calendar': './time/calendar.tsx',
  'time-clock-clockwise': './time/clockClockwise.tsx',
  'time-hourglass': './time/hourglass.tsx',
};

export default timeIconStore;
