import styles from './button.module.scss';
import type { ButtonClassNameAssoc } from './interfaces';

export const DEFAULT_BUTTON_TEST_ID = 'XYZ.Button';

export const DEFAULT_LINK_BUTTON_TEST_ID = 'XYZ.LinkButton';

export const DEFAULT_CLASS_NAME_ASSOC: ButtonClassNameAssoc = {
  colorSchema: {
    'color-dark-solid': styles._colorDarkSolid,
    'color-light-solid': styles._colorLightSolid,
    'color-primary-solid': styles._colorPrimarySolid,
    'color-secondary-solid': styles._colorSecondarySolid,
    'color-informative-solid': styles._colorInformativeSolid,
    'color-positive-solid': styles._colorPositiveSolid,
    'color-attention-solid': styles._colorAttentionSolid,
    'color-negative-solid': styles._colorNegativeSolid,
    'color-dark-elevate': styles._colorDarkElevate,
    'color-dark-ghost': styles._colorDarkGhost,
    'color-dark-ghost-outline': styles._colorDarkGhostOutline,
    'color-light-elevate': styles._colorLightElevate,
    'color-light-ghost': styles._colorLightGhost,
    'color-light-ghost-outline': styles._colorLightGhostOutline,
    'color-primary-elevate': styles._colorPrimaryElevate,
    'color-primary-ghost': styles._colorPrimaryGhost,
    'color-primary-ghost-outline': styles._colorPrimaryGhostOutline,
    'color-secondary-elevate': styles._colorSecondaryElevate,
    'color-secondary-ghost': styles._colorSecondaryGhost,
    'color-secondary-ghost-outline': styles._colorSecondaryGhostOutline,
    'color-informative-elevate': styles._colorInformativeElevate,
    'color-informative-ghost': styles._colorInformativeGhost,
    'color-informative-ghost-outline': styles._colorInformativeGhostOutline,
    'color-positive-elevate': styles._colorPositiveElevate,
    'color-positive-ghost': styles._colorPositiveGhost,
    'color-positive-ghost-outline': styles._colorPositiveGhostOutline,
    'color-attention-elevate': styles._colorAttentionElevate,
    'color-attention-ghost': styles._colorAttentionGhost,
    'color-attention-ghost-outline': styles._colorAttentionGhostOutline,
    'color-negative-elevate': styles._colorNegativeElevate,
    'color-negative-ghost': styles._colorNegativeGhost,
    'color-negative-ghost-outline': styles._colorNegativeGhostOutline,
    'state-active-solid': styles._stateActiveSolid,
    'state-disabled-solid': styles._stateDisabledSolid,
    'state-pending-solid': styles._statePendingSolid,
    'state-success-solid': styles._stateSuccessSolid,
    'state-warning-solid': styles._stateWarningSolid,
    'state-error-solid': styles._stateErrorSolid,
    'state-active-elevate': styles._stateActiveElevate,
    'state-active-ghost': styles._stateActiveGhost,
    'state-active-ghost-outline': styles._stateActiveGhostOutline,
    'state-disabled-elevate': styles._stateDisabledElevate,
    'state-disabled-ghost': styles._stateDisabledGhost,
    'state-disabled-ghost-outline': styles._stateDisabledGhostOutline,
    'state-pending-elevate': styles._statePendingElevate,
    'state-pending-ghost': styles._statePendingGhost,
    'state-pending-ghost-outline': styles._statePendingGhostOutline,
    'state-success-elevate': styles._stateSuccessElevate,
    'state-success-ghost': styles._stateSuccessGhost,
    'state-success-ghost-outline': styles._stateSuccessGhostOutline,
    'state-warning-elevate': styles._stateWarningElevate,
    'state-warning-ghost': styles._stateWarningGhost,
    'state-warning-ghost-outline': styles._stateWarningGhostOutline,
    'state-error-elevate': styles._stateErrorElevate,
    'state-error-ghost': styles._stateErrorGhost,
    'state-error-ghost-outline': styles._stateErrorGhostOutline,
  },
  shape: {
    rounded: '',
    circular: styles._shape_circular,
  },
  size: {
    '2xl': styles._size_2xl,
    xl: styles._size_xl,
    l: styles._size_l,
    m: styles._size_m,
    s: styles._size_s,
    xs: styles._size_xs,
  },
  border: {
    always: styles._bordered_always,
  },
  loading: styles._loading,
} as const;
