/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedButtonProps {
  size?: '2xl' | 'xl' | 'l' | 'm' | 's' | 'xs';
  shape?: 'circular' | 'rounded';
  state?: 'pending' | 'success' | 'warning' | 'error';
  appearance?: 'dark' | 'light' | 'primary' | 'secondary' | 'informative' | 'positive' | 'attention' | 'negative';
  variant?: 'solid' | 'elevate' | 'ghost' | 'ghost-outline';
}
