/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedInputProps {
  size?: '2xl' | 'xl' | 'l' | 'm' | 's' | 'xs';
  shape?: 'circular' | 'rounded';
  state?: 'success' | 'error';
}
