/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GeneratedIconProps {
  size?: '2xl' | 'xl' | 'l' | 'm' | 's' | 'xs';
  shape?: 'circular' | 'rounded';
  appearance?:
    | 'transparent'
    | 'dark'
    | 'light'
    | 'neutral'
    | 'primary'
    | 'secondary'
    | 'informative'
    | 'positive'
    | 'attention'
    | 'negative';
}
